# Generated by Django 4.1.5 on 2023-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joburi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
